/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const SiteConfig = IDL.Record({
  'inviteCode' : IDL.Text,
  'registrationLink' : IDL.Text,
});

export const idlService = IDL.Service({
  'getConfig' : IDL.Func([], [SiteConfig], ['query']),
  'incrementVisitorCount' : IDL.Func([], [IDL.Nat], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const SiteConfig = IDL.Record({
    'inviteCode' : IDL.Text,
    'registrationLink' : IDL.Text,
  });
  
  return IDL.Service({
    'getConfig' : IDL.Func([], [SiteConfig], ['query']),
    'incrementVisitorCount' : IDL.Func([], [IDL.Nat], []),
  });
};

export const init = ({ IDL }) => { return []; };